### ISSUE TITLE
isTorchOn no longer working

### ISSUE THREAD

**Issue by mhesham93** [twostraws/CodeScanner#117]
For some reason the isTorchOn no longer works. It turns on for a second then turns off on it's own. 

iOS 16.6.1

**Comment by nitricware** [comment]
Are you sure you're using the most recent version? This should be fixed in #85 ...

**Comment by nitricware** [comment]
Sorry, I meant the most recent CodeScanner version not iOS version (2.3.3)

Because exactly what you describe happened to me in versions prior.

I currently have an App published that uses CodeScanner 2.3.3 and it does not have that issue: https://apps.apple.com/at/app/pstart/id1488221355?l=en-GB
