### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by cyrillelegrand** [twostraws/CodeScanner#123]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by twostraws** [comment]
No, we don't need to include it.

**Comment by twostraws** [comment]
I hope you can appreciate I'm not in a position to give advice on Apple's policies 🙂

**Comment by cyrillelegrand** [comment]
Agreed. Thanks for your quick replies anyway!
