### ISSUE TITLE
CodeScanner Fails on macOS Due to UIKit Dependency

### ISSUE THREAD

**Issue by enriquesouza** [twostraws/CodeScanner#126]
Hello CodeScanner Team,

I've encountered an issue while integrating CodeScanner into a project that targets both iOS and macOS platforms. The problem arises specifically when the target is set to macOS, leading to errors related to UIKit dependencies. It appears that CodeScanner is relying on UIKit, which is not available on macOS. This limitation restricts the use of CodeScanner to iOS targets only.

### Environment
- CodeScanner version: 2.3.3
- Xcode version: Version 15.2 (15C500b)
- macOS version: 14.4 Beta (23E5180j)
- Swift version: 
Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

### Steps to Reproduce
1. Integrate CodeScanner into a SwiftUI project that targets macOS.
2. Attempt to compile the project with macOS as the target.
3. Observe compilation errors related to UIKit dependencies.

### Expected Behavior
I expected CodeScanner to be compatible with macOS, possibly through AppKit or a cross-platform SwiftUI implementation, allowing the same codebase to support scanning functionalities across both iOS and macOS.

### Actual Behavior
The project fails to compile for macOS targets due to UIKit dependency errors. The error messages indicate that UIKit components are being referenced, which are not available on macOS.

### Suggested Solution
If feasible, it would be beneficial to explore adapting CodeScanner to support macOS by abstracting UIKit dependencies or providing a SwiftUI-based solution that is compatible with both iOS and macOS platforms.

I'm looking forward to your insights or any workarounds you might suggest for this issue. Thank you for your efforts in developing CodeScanner, and I appreciate any assistance you can provide to make it more versatile across Apple's ecosystem.

<img width="1107" alt="image" src="https://github.com/twostraws/CodeScanner/assets/1700699/094d4560-b8fd-409d-a4d0-6a79a970989b">

**Comment by praveentcom** [comment]
+1

**Comment by nathanfallet** [comment]
That would be a big rewrite, because it's currently made as a SwiftUI wrapper of UIKit code.
This library was thought for mobile devices, because you usually scan barcodes with a phone or a tablet, not a computer.
