### ISSUE TITLE
Support Privacy Manifest

### ISSUE THREAD

**Issue by benMohamed** [twostraws/CodeScanner#133]
while I understand that your SDK is not singled out on Apple's list, my reading of the [new requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)]" applies to app submissions as a whole, meaning that if CodeScanner does not provide a privacy manifest, the app submission will be rejected.

**Comment by benMohamed** [comment]
I'm getting emails back from Apple about this because your library is not compliant.

ITMS-91053: Missing API declaration - Your app’s code in the “YourApp” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by minhdai92** [comment]
I'm facing with this issue too. could you please help us apply Manifest for this library asap, many thank ^^

**Comment by david-hosier** [comment]
@benMohamed  Have you looked through the CodeScanner code to see if you can identify which APIs you think it's using that needs to be reported? I read through the list of APIs that trigger the requirement from the link you included, and then I looked through all the code in this repo and was unable to readily find any use of offending APIs. The message you shared from Apple seems to indicate use of UserDefaults, but I don't see any use of that API in this repo. Are we sure this email is solely a result of your use of the CodeScanner dependency and not specific to your app?

I was hoping to help out by contributing the necessary privacy manifest, but I'm honestly not sure what would need to be in it after reviewing the guidelines and the code or if it's even necessary for this project. Paul indicated in #123 that this project does not need it.

**Comment by twostraws** [comment]
@david-hosier At this point very few people – myself included – really seem to understand what's going on. If you think this project needs one, and you're willing to contribute it, please go for it!

**Comment by benMohamed** [comment]
@twostraws I opened this PR https://github.com/twostraws/CodeScanner/pull/138 to fix that issue.

**Comment by nathanfallet** [comment]
Fixed and released!
