### ISSUE TITLE
Support Privacy Manifest

### ISSUE THREAD

**Issue by benMohamed** [twostraws/CodeScanner#135]
I'm getting emails back from Apple about this because your library is not compliant.

> ITMS-91053: Missing API declaration - Your app’s code in the “YourApp” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

**Comment by twostraws** [comment]
Please don't open duplicate issues. This is an open source project – you're welcome to contribute a solution.
