### ISSUE TITLE
German umlauts cannot be encoded.

### ISSUE THREAD

**Issue by samy4sam** [twostraws/CodeScanner#17]

**Comment by twostraws** [comment]
Can I suggest you investigate the problem and consider submitting a fix? It's challenging for me to reproduce this kind of problem.

**Comment by kaiwinter** [comment]
German umlauts are working just fine:

![Screen Shot 2022-03-08 at 13 51 05](https://user-images.githubusercontent.com/110982/157242171-832d0d21-4e9c-4963-9b43-a6d221c33f0d.png)

**Comment by NathanFallet** [comment]
Closing as it seems to be fixed. Please reopen if it occurs again.
