### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by ichbineinnerd0** [twostraws/CodeScanner#22]
I've looked over everything, and I can’t see a way to use the front camera. I was wondering if I have missed something, and if not, how difficult it would be to implement. I don't have a very in-depth knowledge to Swift, but I have tried to look over some possibilities of how to do it, but achieved nothing

**Comment by AxelSariel** [comment]
Not sure how needed is this as of now, but what I did was download the package, add it as a local package in Xcode, and edit line 170 of CodeScanner to the following:

```
let videoCaptureDevice = AVCaptureDevice.default(.builtInWideAngleCamera,for: .video, position: .front)
```

It would be nice to take this in as an argument when calling the scanner!

See more on [Apple's Developer Website](https://developer.apple.com/documentation/avfoundation/avcapturedevice/position)

**Comment by NathanFallet** [comment]
@ichbineinnerd0 @AxelSariel I added an argument to `CodeScannerView` in my Pull Request #52 regarding `videoCaptureDevice`
