### ISSUE TITLE
Use View controller as a coordinator

### ISSUE THREAD

**Issue by breyed** [twostraws/CodeScanner#30]
The implementation in CodeScanner.swift creates a coordinator instance to adopt AVCaptureMetadataOutputObjectsDelegate. Is there an advantage to using a coordinator instead of having ScannerViewController adopt the delegate?

The intent of a coordinator in SwiftUI seems to be to host delegates when you're using existing ViewController. In this case, since a custom ViewController is needed, there doesn't seem to be any need for a second class.

**Comment by NathanFallet** [comment]
I'm going to take a look if this refactor can be done and works.
