### ISSUE TITLE
Please change `select` to `load` to display correctly on 4.7" Simulators.

### ISSUE THREAD

**Issue by stuffmc** [twostraws/CodeScanner#32]
https://github.com/twostraws/CodeScanner/blob/cbe8bf4ddc084c9a23f6d9593a513b9637b24ace/Sources/CodeScanner/CodeScanner.swift#L99

![Simulator Screen Shot - iPod touch (7th generation) - 2021-05-24 at 15 20 33](https://user-images.githubusercontent.com/66973/119353773-988cfd80-bca3-11eb-9432-0ac5cb9c9f94.png)

**Comment by twostraws** [comment]
I've replaced it with "Select a custom image" in 2.0.0.
