### ISSUE TITLE
Mac OS Catalyst Support

### ISSUE THREAD

**Issue by janandre** [twostraws/CodeScanner#33]
Hi Paul,

We use mac catalyst (big sur) as the minimum version for our app.
CodeScanner has build errors, as its min version is iOS13 and the AV Classes used are only available in Big Sur (Catalyst iOS 14).

For now, I have forked the project and raised it to iOS 14. 
This fixes our build issue on Mac.

Is there a way you could change the package.swift within this repo, so we can drop our fork?

Thanks a lot!
Best regards,
Jan André

**Comment by twostraws** [comment]
If you're asking us to move the base deployment target up to iOS 14 I'm not sure that's a good idea - it would help you, but hurt others. Is it possible you can make your change using `#available` or similar? If so, I'd be happy to merge a PR from you.
