### ISSUE TITLE
Updated Swift Package?

### ISSUE THREAD

**Issue by MikeMilzz** [twostraws/CodeScanner#35]
Thanks Paul for another great resource. I was looking through the issues and definitely want to dig more into adding a torch and front camera option, but in reviewing the various pull request I noticed that you recently added a viewfinder option that doesn't show in the published Swift package. Do you need to bump the version to get that to show up for people using the Swift Package through XCode? I apologize if I'm not doing something correctly - Swift packages are new to me.

**Comment by cymr0** [comment]
@MikeMilzz  You can change it from version to be the branch, or a specific commit. I'm using main branch for some of the recent changes.

**Comment by MikeMilzz** [comment]
Thanks @cymr0 . I took another look at the options and switched to following a branch instead of a version and that did the trick. I'll close this issue out as a non-issue and a lesson learned for me.
