### ISSUE TITLE
Turning off vibration on scan

### ISSUE THREAD

**Issue by deepak013** [twostraws/CodeScanner#36]
There is no feature to turning vibration on and off. Can you please add this in next release.

**Comment by Matthijn** [comment]
This indeed. I'd like to be able to have a different vibration on an invalid scan (eg the QR may be valid to scan, but is not known in my system). If I could toggle the vibration off here, then it would be not an issue.

**Comment by pgz285** [comment]
Changing this place to 1520 can change the intensity of the vibration 
![image](https://user-images.githubusercontent.com/66555198/132822511-cbd0f46b-a43d-46cc-af45-4d732e82fffb.png)

**Comment by twostraws** [comment]
Vibration is enabled by default in 2.0.0, but can be disabled by passing `shouldVibrateOnSuccess: false` into the initializer.
