### ISSUE TITLE
Code scanner failed on iOS 13.3.1

### ISSUE THREAD

**Issue by laboratoryyingong** [twostraws/CodeScanner#39]
Hi,
I have tried to implement CodeScanner on iOS 13.3.1. After I approved the camera access, the view keeps in black.  I tried on iOS 14, it works. I would like to report this issue because some projects still support 13. 

Thanks & Regards!
Max

**Comment by twostraws** [comment]
I can't resolve this without any further information, I'm afraid.

**Comment by NathanFallet** [comment]
I think it was linked to the permission flow, which should be fixed now. Please reopen if the issue still occurs.
