### ISSUE TITLE
allow user to cancel

### ISSUE THREAD

**Issue by mvolkmann** [twostraws/CodeScanner#45]
Is there a way I can add a button over the CodeScanner to allow the user to cancel their request to scan?
I see that they can just slide the sheet down to dismiss it, but I'm concerned that won't be discoverable by a user.

**Comment by twostraws** [comment]
If you want to add a cancel button, wrap the code scanner in a `NavigationView`, then add any toolbar contents you want. This is much more customizable than us trying to cater for a variety of toolbar configurations.
