### ISSUE TITLE
Command CompileSwiftSources failed with a nonzero exit code

### ISSUE THREAD

**Issue by mxnmike** [twostraws/CodeScanner#48]
I don't know what to do, it won't build, I tried already cleaning derived data folder, restarted Xcode, re-installed Xcode also, try to run in my device and nothing... anyone has an idea on how to fix this?

Im using Monterey 12.0.1 and Xcode 13.2
Thanks

<img width="1365" alt="Screen Shot 2021-12-15 at 3 20 44 p m" src="https://user-images.githubusercontent.com/13444751/146280012-377eeee7-16dc-442d-9861-4a8cc0d96511.png">

**Comment by SandnerSoft** [comment]
@mxnmike 

are you using the latest version 2.0.0?
I have the same environment and it runs without problems.

**Comment by NathanFallet** [comment]
There was big problems with Swift Package manager in Xcode 13.2, try to update to Xcode 13.2.1

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/30439790/146931251-3e185437-5b2f-44ad-b1b2-5caa610b77fe.png">

**Comment by mxnmike** [comment]
The update fixed my issue... thanks
