### ISSUE TITLE
Front camera option

### ISSUE THREAD

**Issue by maikelsgit** [twostraws/CodeScanner#54]
I would like to use the codescanner on my iPad and use the front facing camera.
Can you please add the option to select the front facing camera.

Thanks!!

**Comment by cymr0** [comment]
I think a recent update means you can already do this with the videoCaptureDevice parameter:

`videoCaptureDevice: AVCaptureDevice.default(.builtInWideAngleCamera, for: .video, position: .front),`

I think this gives you what you need? Hope this helps.

**Comment by daver234** [comment]
This worked for me.  Thanks.

**Comment by NathanFallet** [comment]
I'm going to add the option as a parameter in a future update. Thanks for the suggestion!

**Comment by NathanFallet** [comment]
Checked, it as been added as a parameter in the initializer.
