### ISSUE TITLE
Cannot build for Mac Catalyst

### ISSUE THREAD

**Issue by Terabyte1385** [twostraws/CodeScanner#56]
This package claims to be able to run on Mac Catalyst 14 or later, but I cannot build my project for Mac Catalyst because some `@available` lines are missing (according to Xcode). 

Errors Found:
`ScannerViewController.swift:12:11: 'CodeScannerView' is only available in Mac Catalyst 14.0 or newer`
`ScannerCoordinator.swift:12:11: 'CodeScannerView' is only available in Mac Catalyst 14.0 or newer`
`CodeScanner.swift:32:22: 'AVMetadataObject' is only available in Mac Catalyst 14.0 or newer`

If it matters, the project is aimed at iOS 15 and macOS 12.

AVMetadataObject, for example, requires Mac Catalyst 14 or later, and this package is capable to handle AVMetadataObject correctly, but for some reason Xcode cannot build.

**Comment by Terabyte1385** [comment]
<img width="271" alt="Screenshot 2022-02-03 at 20 04 12" src="https://user-images.githubusercontent.com/78782971/152402153-3f7e322b-521e-4012-add2-39df00396a89.png">

**Comment by garthvh** [comment]
I am having the same issue macOS 12, catalyst 15

**Comment by NgocLK** [comment]
I'm having the same issue, can anyone help?
