### ISSUE TITLE
connot update isGalleryPresented wrappedValue.

### ISSUE THREAD

**Issue by Norlt** [twostraws/CodeScanner#67]
cause Error : - Modifying state during view update, this will cause undefined behavior. 
ScannerViewController,isGalleryShowing didSet.
<img width="1436" alt="截屏2022-05-28 09 32 51" src="https://user-images.githubusercontent.com/93469537/170805281-ff15505b-2755-4dfb-a5fe-a9cc7ffd79d6.png">

**Comment by NathanFallet** [comment]
Can you share the piece of code where you call `openGallery` or change `isGalleryPresented`'s value?

**Comment by Kurris** [comment]
Also meet this issue when slide down the Gallery Sheet, only work fine through the Cancel Button

**Comment by kafejo** [comment]
Fixed here https://github.com/twostraws/CodeScanner/pull/106
