### ISSUE TITLE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by lovlamba** [twostraws/CodeScanner#72]
The app crashes with this testing it in a physical device. The error comes in the ScannerViewController while passing the session as a parameter.

**Comment by PatroSV19** [comment]
This issue has been solved by @uniqby. 

Git clone https://github.com/uniqby/CodeScanner.git

Follow this tutorial to create a local dependency: https://www.youtube.com/watch?v=7rFPvj7yu4Q

Replace ScannerViewController.swift with the one from the cloned repository. 

Worked out for me!
