### ISSUE TITLE
cannot find 'delegate' in scope

### ISSUE THREAD

**Issue by MuratBatarayPXL** [twostraws/CodeScanner#82]
Issue found in ScannerViewController.swift on line 122, 128 and 129 in the function touchesBegan()

**Comment by MuratBatarayPXL** [comment]
im guessing you replace delegate?.parent with parentView?

**Comment by NathanFallet** [comment]
The compiler did not warned me about this issue because it's only for the simulator. I'm going to fix it now

**Comment by MuratBatarayPXL** [comment]
Thanks!

**Comment by NathanFallet** [comment]
It's available in 2.2.1, you can reset your swift package cache
