### ISSUE TITLE
Dismiss/cancel not discoverable

### ISSUE THREAD

**Issue by rocketraman** [twostraws/CodeScanner#86]
Say a user opens up the scanner sheet. If they are aware of the fact that a modal sheet was just used, they can swipe down to dismiss it. However, the default view being pretty much full-screen means most users remain unaware that a sheet is active, and do not know how to dismiss/cancel the scanner view.

Can some options be added to make how to cancel/dismiss a scanner view more discoverable? Either an option to add some kind of close/cancel button, OR have the sheet show up as smaller than the full screen, say at 75 or 80% of the screen instead.

Sheets are supposed to have a presentation detents feature for iOS 15 and up -- not sure if that can help here.

**Comment by rocketraman** [comment]
I do see issue https://github.com/twostraws/CodeScanner/issues/45. Having an explicit wrapper with navigation seems like a good workaround, though its not trivial on the caller (at least I haven't gotten it to work properly yet).

I still think it is valid to think about supporting detents as those are the standard way sheet gestures are supposed to be discoverable.

**Comment by NathanFallet** [comment]
Even when presenting a modal you have to wrap your view into a navigation view with the cancel button (the navigation view inside the modal)
