### ISSUE TITLE
Crashing when no camera permissions set yet

### ISSUE THREAD

**Issue by schultzjim** [twostraws/CodeScanner#87]
I am getting a crash in `ScannerViewController` line 178 when there are no camera permissions set yet, it presents the permissions prompt but then crashes. after approving and relaunching it no longer crashes. I'm happy to help out with a fix etc just wanted to submit this first.

**Comment by ian-sayles** [comment]
Hi Jim

Are you using the latest version, for I had similar issue which was just recently fixed.
https://github.com/twostraws/CodeScanner/issues/77#issue-1343243500

Since upgrading to version 2.2.1, I have had no issues.

**Comment by schultzjim** [comment]
@ian-sayles that did that trick, thanks
