### ISSUE TITLE
Restarting scanner

### ISSUE THREAD

**Issue by luciano88** [twostraws/CodeScanner#9]
When a qr Code is detected, `codeFound` is set to true and the scanner stops detecting new codes, even if I refresh the view (the coordinator is not initialized again). How can I restart the scanner after the `completion` is executed?

**Comment by rajubd49** [comment]
I'm also facing the same issue.

**Comment by rajubd49** [comment]
I'm also facing the same issue. Please check the fix here at https://github.com/rajubd49/CodeScanner/commit/b3d07fa60c2a48d42ef8b1e550d4ff95b040a636

I've created a pull request for this fix.

**Comment by twostraws** [comment]
@rajubd49 Thank you!

**Comment by haemi** [comment]
how does the restart work? Do you use the coordinator for that?
