### ISSUE TITLE
How can i change location of gallery button ?

### ISSUE THREAD

**Issue by sametkarakurt** [twostraws/CodeScanner#91]
CodeScannerView(codeTypes: [.qr],manualSelect: true,showViewfinder:true, completion: handleScan)
I added manual select but gallery button overflow to navbar. I want to change location of gallery button. How can ı do it?

**Comment by NathanFallet** [comment]
You can create a custom view, make your own button, and toggle the gallery on demand as done here:
https://github.com/NathanFallet/BdeEnsisaMobile/blob/main/iosApp/iosApp/Features/Scanner/ScannerView.swift
