### ISSUE TITLE
html link result

### ISSUE THREAD

**Issue by FelixKAcheampong** [twostraws/CodeScanner#96]
The content of the result.string is an html link to a site instead of the qr or barcode code or number

**Comment by NathanFallet** [comment]
Please provide more details, and information to reproduce.

**Comment by FelixKAcheampong** [comment]
The result of the qrcode is 
http://qr.rs/v/675a0

`CodeScannerView(codeTypes: [.code128,.qr,.aztec,.code39,.code93,.code39Mod43],showViewfinder: true,shouldVibrateOnSuccess: true) { response in
                if case let .success(result) = response {
                    print("Found code: \(result.string)")
                    var t: Int = 0
                    switch result.type {
                        case .code128: t=1;break
                        case .qr: t=2;break
                        case .aztec: t=3;break
                        case .code39: t=4;break
                        case .code93: t=5;break
                        case .code39Mod43: t=6;break
                    default:
                        print("")
                    }
                    self.type = t
                    self.value = result.string
                    self.showSheet = false
                }
            }`

**Comment by NathanFallet** [comment]
@FelixKAcheampong I don't see what's the problem here. It returns the content of your QR Code, which is this link. Try scanning the code with any other tool and you will get the same link.
