### ISSUE TITLE
Multiple Camera shutter noises with the 2.3.0 release

### ISSUE THREAD

**Issue by Furthermoore** [twostraws/CodeScanner#99]
I recently updated my CodeScanner lib from 1.1.0 to 2.3.0 and a QA engineer noticed several repetitive camera shutter sounds when scanning a QR code.  I couldn't reproduce it on my end;  He has an iPhone 14 Pro and I have an iPhone SE.

Anyway, I went looking for ways to silence this camera noise when using AVFoundation and came across a few posts on the interwebs: 
[https://enebin.medium.com/swiftui-how-to-turn-off-or-change-camera-shutter-sound-ecfa604394f0](url)
and 
[https://stackoverflow.com/questions/4401232/avfoundation-how-to-turn-off-the-shutter-sound-when-capturestillimageasynchrono](url)

So I then went looking for usage of `AVCapturePhotoCaptureDelegate` api and noticed you added it in the 2.3.0 release of CodeScanner.

So I reverted our library back to CodeScanner 2.2.1 and then the issue went away on his iPhone 14 Pro.

I wish I could share more, but my codebase is private.  Anyway, I just wanted to give a heads up as I'm wondering if anyone else has noticed this.

**Comment by NathanFallet** [comment]
@Furthermoore Can you try using branch `fix/shutter-noises` and tell me if it solves your problem?

**Comment by Furthermoore** [comment]
@NathanFallet yep, that solved it.

**Comment by NathanFallet** [comment]
Perfect! I'm going to publish a release then.

**Comment by theedov** [comment]
I actually experience this issue in 2.5.2. 
https://github.com/twostraws/CodeScanner/issues/163
